"""rename department

Revision ID: 761b49ec37ee
Revises: 312d6ed875bf
Create Date: 2024-02-14 20:47:21.080616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761b49ec37ee'
down_revision = '312d6ed875bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
